provider:
  name: faas
  gateway: http://localhost:8080

functions:
  astro-finder:
    lang: python3
    handler: ./astro-finder
    image: foenix/astro-finder
    environment:
      write_debug: true
